fix(workflow): Fixed palette checker

diff --git a/.github/workflows/palette-check.yml b/.github/workflows/palette-check.yml
--- a/.github/workflows/palette-check.yml
+++ b/.github/workflows/palette-check.yml
@@ -29,43 +29,113 @@ jobs:
         run: |
           git fetch origin "$BASE_REF"
 
-          diff_changes=$(git diff -U10000 origin/$BASE_REF...HEAD |
-            awk '/^diff --git.*manifest\.json /{found=1} /^diff --git/{if(!/\.json /) found=0} found{print}' |
-            grep -vE "^(index|\+\+\+|-)") || echo "No manifest.json file changed"
+          diff_changes=$(git diff -U10000 --name-only --diff-filter=ACMRT origin/"$BASE_REF"...HEAD | grep '\.json$' || true)
 
           if [ -z "$diff_changes" ]; then
-            echo "No diff changes found!"
+            echo "No json files changed!"
             echo "The base ref checking: $BASE_REF"
             echo "The head ref checking: $HEAD_REF"
             exit 0
           fi
 
+          declare -A table
+
+          # Key is the path to the json field, value is the type of field
+          table["dark"]="object"
+          table["dark.mPrimary"]="string"
+          table["dark.mOnPrimary"]="string"
+          table["dark.mSecondary"]="string"
+          table["dark.mOnSecondary"]="string"
+          table["dark.mTertiary"]="string"
+          table["dark.mOnTertiary"]="string"
+          table["dark.mError"]="string"
+          table["dark.mOnError"]="string"
+          table["dark.mSurface"]="string"
+          table["dark.mOnSurface"]="string"
+          table["dark.mSurfaceVariant"]="string"
+          table["dark.mOnSurfaceVariant"]="string"
+          table["dark.mOutline"]="string"
+          table["dark.mShadow"]="string"
+          table["dark.mHover"]="string"
+          table["dark.mOnHover"]="string"
+
+          table["dark.terminal"]="object"
+          table["dark.terminal.foreground"]="string"
+          table["dark.terminal.background"]="string"
+          table["dark.terminal.selectionFg"]="string"
+          table["dark.terminal.selectionBg"]="string"
+          table["dark.terminal.cursorText"]="string"
+          table["dark.terminal.cursor"]="string"
+
+          table["dark.terminal.normal"]="object"
+          table["dark.terminal.normal.black"]="string"
+          table["dark.terminal.normal.red"]="string"
+          table["dark.terminal.normal.green"]="string"
+          table["dark.terminal.normal.yellow"]="string"
+          table["dark.terminal.normal.blue"]="string"
+          table["dark.terminal.normal.magenta"]="string"
+          table["dark.terminal.normal.cyan"]="string"
+          table["dark.terminal.normal.white"]="string"
+
+          table["dark.terminal.bright"]="object"
+          table["dark.terminal.bright.black"]="string"
+          table["dark.terminal.bright.red"]="string"
+          table["dark.terminal.bright.green"]="string"
+          table["dark.terminal.bright.yellow"]="string"
+          table["dark.terminal.bright.blue"]="string"
+          table["dark.terminal.bright.magenta"]="string"
+          table["dark.terminal.bright.cyan"]="string"
+          table["dark.terminal.bright.white"]="string"
+
+          table["light"]="object"
+          table["light.mPrimary"]="string"
+          table["light.mOnPrimary"]="string"
+          table["light.mSecondary"]="string"
+          table["light.mOnSecondary"]="string"
+          table["light.mTertiary"]="string"
+          table["light.mOnTertiary"]="string"
+          table["light.mError"]="string"
+          table["light.mOnError"]="string"
+          table["light.mSurface"]="string"
+          table["light.mOnSurface"]="string"
+          table["light.mSurfaceVariant"]="string"
+          table["light.mOnSurfaceVariant"]="string"
+          table["light.mOutline"]="string"
+          table["light.mShadow"]="string"
+          table["light.mHover"]="string"
+          table["light.mOnHover"]="string"
+
+          table["light.terminal"]="object"
+          table["light.terminal.foreground"]="string"
+          table["light.terminal.background"]="string"
+          table["light.terminal.selectionFg"]="string"
+          table["light.terminal.selectionBg"]="string"
+          table["light.terminal.cursorText"]="string"
+          table["light.terminal.cursor"]="string"
+
+          table["light.terminal.normal"]="object"
+          table["light.terminal.normal.black"]="string"
+          table["light.terminal.normal.red"]="string"
+          table["light.terminal.normal.green"]="string"
+          table["light.terminal.normal.yellow"]="string"
+          table["light.terminal.normal.blue"]="string"
+          table["light.terminal.normal.magenta"]="string"
+          table["light.terminal.normal.cyan"]="string"
+          table["light.terminal.normal.white"]="string"
+
+          table["light.terminal.bright"]="object"
+          table["light.terminal.bright.black"]="string"
+          table["light.terminal.bright.red"]="string"
+          table["light.terminal.bright.green"]="string"
+          table["light.terminal.bright.yellow"]="string"
+          table["light.terminal.bright.blue"]="string"
+          table["light.terminal.bright.magenta"]="string"
+          table["light.terminal.bright.cyan"]="string"
+          table["light.terminal.bright.white"]="string"
+
           comment_body=$(printf -- '### Automatic Palette Check')
 
           issues=0
-          line_index=0
-
-          l_priority="[(L)]($PR_NUMBER 'Low priority, it is okay for this to remain unfixed before merging')"
-          h_priority="[(H)]($PR_NUMBER 'High priority, this needs to be fixed for the PR to be merged')"
-
-          function print_line() {
-            check_file_title
-
-            local priority=$1
-            local index=$2
-            local comment=$3
-            local code_line=$4
-            comment_body+=$(printf -- '\n- %s Line %d: %s\n```json\n%s\n```' "$priority" "$index" "$comment" "$code_line")
-          }
-
-          function print_missing_property() {
-            check_file_title
-
-            local priority=$1
-            local property=$2
-            local code_line=$3
-            comment_body+=$(printf -- '\n- %s Missing required property `%s`. For example:\n```json\n%s\n```' "$priority" "$property" "$code_line")
-          }
 
           # PR Comment Title
           title_added=false
@@ -77,283 +147,21 @@ jobs:
             fi
           }
 
-          # Required Properties in Components
-          current_indent=0
-
-          # First indent
-          inJson=false
-
-          # Second indent
-          inDark=false
-          inLight=false
-
-          # Third indent
-          inTerminal=false
-
-
-          # Fourth indent
-          inNormal=false
-          inBright=false
-
-
-          # Required properties in the root
-          hasDark=false
-          hasLight=false
-
-          # Required properties in light / dark
-          hasMPrimary=false
-          hasMOnPrimary=false
-          hasMSecondary=false
-          hasMOnSecondary=false
-          hasMTertiary=false
-          hasMOnTertiary=false
-          hasMError=false
-          hasMOnError=false
-          hasMSurface=false
-          hasMOnSurface=false
-          hasMSurfaceVariant=false
-          hasMOnSurfaceVariant=false
-          hasMOutline=false
-          hasMShadow=false
-          hasMHover=false
-          hasMOnHover=false
-          hasTerminal=false
-
-          function reset_indent_1() {
-            hasMPrimary=false
-            hasMOnPrimary=false
-            hasMSecondary=false
-            hasMOnSecondary=false
-            hasMTertiary=false
-            hasMOnTertiary=false
-            hasMError=false
-            hasMOnError=false
-            hasMSurface=false
-            hasMOnSurface=false
-            hasMSurfaceVariant=false
-            hasMOnSurfaceVariant=false
-            hasMOutline=false
-            hasMShadow=false
-            hasMHover=false
-            hasMOnHover=false
-            hasTerminal=false
-
-            reset_indent_1
-          }
-
-
-          # Required properties in terminal
-          hasNormal=false
-          hasBright=false
-          hasForeground=false
-          hasBackground=false
-          hasSelectionFg=false
-          hasSelectionBg=false
-          hasCursorText=false
-          hasCursor=false
-
-          function reset_indent_2() {
-            inTerminal=false
-
-            hasNormal=false
-            hasBright=false
-            hasForeground=false
-            hasBackground=false
-            hasSelectionFg=false
-            hasSelectionBg=false
-            hasCursorText=false
-            hasCursor=false
-
-            reset_indent_3
-          }
-
-
-          # Required properties in terminal in normal/bright
-          hasBlack=false
-          hasRed=false
-          hasGreen=false
-          hasYellow=false
-          hasBlue=false
-          hasMagenta=false
-          hasCyan=false
-          hasWhite=false
-
-          function reset_indent_3() {
-            inNormal=false
-            inBright=false
-
-            hasBlack=false
-            hasRed=false
-            hasGreen=false
-            hasYellow=false
-            hasBlue=false
-            hasMagenta=false
-            hasCyan=false
-            hasWhite=false
-          }
-
-          function reset_required_properties() {
-            inManifest=false
-
-            hasId=false
-            hasName=false
-            hasVersion=false
-            hasAuthor=false
-            hasDescription=false
-            hasRepository=false
-          }
-
-          function print_required_properties() {
-            if [ "$hasDark" = false ]; then
-              print_missing_property "$h_priority" 'dark' '"dark": {\n...\n}'
-              issues=$((issues + 1))
-            fi
-            if [ "$hasLight" = false ]; then
-              print_missing_property "$h_priority" 'light' '"light": {\n...\n}'
-              issues=$((issues + 1))
-            fi
-            if [ "$hasMPrimary" = false ]; then
-              print_missing_property "$h_priority" 'primary' '"light": {\n...\n}'
-              issues=$((issues + 1))
-            fi
-            if [ "$hasMOnPrimary" = false ]; then
-              print_missing_property "$h_priority" 'onPrimary' '"light": {\n...\n}'
-              issues=$((issues + 1))
-            fi
-            if [ "$hasMSecondary" = false ]; then
-              print_missing_property "$h_priority" 'secondary' '"light": {\n...\n}'
-              issues=$((issues + 1))
-            fi
-            if [ "$hasMOnSecondary" = false ]; then
-              print_missing_property "$h_priority" 'onSecondary' '"light": {\n...\n}'
-              issues=$((issues + 1))
-            fi
-            if [ "$hasMTertiary" = false ]; then
-              print_missing_property "$h_priority" 'light' '"light": {\n...\n}'
-              issues=$((issues + 1))
-            fi
-            if [ "$hasMOnTertiary" = false ]; then
-              print_missing_property "$h_priority" 'light' '"light": {\n...\n}'
-              issues=$((issues + 1))
-            fi
-            if [ "$hasMError" = false ]; then
-              print_missing_property "$h_priority" 'light' '"light": {\n...\n}'
-              issues=$((issues + 1))
-            fi
-            if [ "$hasMOnError" = false ]; then
-              print_missing_property "$h_priority" 'light' '"light": {\n...\n}'
-              issues=$((issues + 1))
-            fi
-            if [ "$hasMSurface" = false ]; then
-              print_missing_property "$h_priority" 'light' '"light": {\n...\n}'
-              issues=$((issues + 1))
-            fi
-            if [ "$hasMOnSurface" = false ]; then
-              print_missing_property "$h_priority" 'light' '"light": {\n...\n}'
-              issues=$((issues + 1))
-            fi
-            if [ "$hasMSurfaceVariant" = false ]; then
-              print_missing_property "$h_priority" 'light' '"light": {\n...\n}'
-              issues=$((issues + 1))
-            fi
-            if [ "$hasMOnSurfaceVariant" = false ]; then
-              print_missing_property "$h_priority" 'light' '"light": {\n...\n}'
-              issues=$((issues + 1))
-            fi
-            if [ "$hasMOutline" = false ]; then
-              print_missing_property "$h_priority" 'light' '"light": {\n...\n}'
-              issues=$((issues + 1))
-            fi
-            if [ "$hasMShadow" = false ]; then
-              print_missing_property "$h_priority" 'light' '"light": {\n...\n}'
-              issues=$((issues + 1))
-            fi
-            if [ "$hasMHover" = false ]; then
-              print_missing_property "$h_priority" 'light' '"light": {\n...\n}'
-              issues=$((issues + 1))
-            fi
-            if [ "$hasMOnHover" = false ]; then
-              print_missing_property "$h_priority" 'light' '"light": {\n...\n}'
-              issues=$((issues + 1))
-            fi
-            if [ "$hasTerminal" = false ]; then
-              print_missing_property "$h_priority" 'light' '"light": {\n...\n}'
-              issues=$((issues + 1))
-            fi
-          }
-
-
           while IFS= read -r line; do
-            if echo "$line" | grep -E "^diff --git" >/dev/null; then
-              print_required_properties
+            # Check each file that it contains the necessary fields
+            file=$line
+            title_added=false
+            file_title=$(printf -- '\n--- \n### File: %s' "$file")
 
-              reset_required_properties
+            for key in "${!table[@]}"; do
+              if ! jq ".$key | type" "$file" | grep "${table[${key}]}" >/dev/null; then
+                check_file_title
 
-              title_added=false
-              file_title=$(printf -- '\n---\n### File: %s' "$(echo "$line" | sed 's/diff --git a\/\(.*\) .*/\1/g')")
-              echo "Checking file: $file_title"
-
-              if [[ "$file_title" == *.json ]]; then
-                inJson=true
-              fi
-            elif echo "$line" | grep -E "^@@" >/dev/null; then
-              line_index=$(echo "$line" | grep -oE "\+[0-9]+" | grep -oE "[0-9]+")
-              echo "Current line index reset: $line_index"
-            else
-              if echo "$line" | grep '"dark":'; then
-                inDark=true
-                hasDark=true
-              fi
-              if echo "$line" | grep '"light":'; then
-                inLight=true
-                hasLight=true
-              fi
-
-              if echo "$line" | grep '\{' >/dev/null; then
-                current_indent=$((current_indent + 1))
-              fi
-
-              if echo "$line" | grep '}'; then
-
-              fi
-              
-              if echo "$line" | grep '"official": false' >/dev/null; then
-                print_line "$h_priority" "$line_index" "Do not add the 'official' property. It's automatically false and is NOT needed!" "$line"
+                comment_body+=$(printf -- '\n- Missing required property `%s`' "$key")
                 issues=$((issues + 1))
               fi
-              if echo "$line" | grep -oE '"repository": ".*"' | grep -v '"repository": "https://github.com/noctalia-dev/noctalia-plugins"' >/dev/null; then
-                print_line "$h_priority" "$line_index" 'The repository field needs to point to the "https://github.com/noctalia-dev/noctalia-plugins" github repository!' "$line"
-                issues=$((issues + 1))
-              fi
-
-              # Check for required properties
-              if echo "$line" | grep '"id":' >/dev/null; then
-                hasId=true
-                if echo "$line" | grep -vE '"id": "[a-zA-Z\-]+"'; then
-                  print_line "$h_priority" "$line_index" 'The id can only contain small characters [a-z], numbers [0-9] and dashes [-]' "$line"
-                fi
-              fi
-              if echo "$line" | grep '"name":' >/dev/null; then
-                hasName=true
-              fi
-              if echo "$line" | grep '"version":' >/dev/null; then
-                hasVersion=true
-              fi
-              if echo "$line" | grep '"author":' >/dev/null; then
-                hasAuthor=true
-              fi
-              if echo "$line" | grep '"description":' >/dev/null; then
-                hasDescription=true
-              fi
-              if echo "$line" | grep '"repository":' >/dev/null; then
-                hasRepository=true
-              fi
-              line_index=$((line_index + 1))
-            fi
+            done
           done <<<"$diff_changes"
-
-          # Print any required properties not printed on a new file found.
-          print_required_properties
 
           if [[ "$issues" -ne 0 ]]; then
             gh pr comment "$PR_NUMBER" --body "$comment_body"
